version: '3'

services:
  yapi-mongo:
    image: mongo:4
    container_name: yapi-mongo
    ports:
      - 27017:27017
    networks:
      - yapi-net
  yapi-web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: yapi:v192
    container_name: yapi-web
    ports:
      - 3000:3000
      - 9090:9090
    depends_on:
      - yapi-mongo
#    volumes:
#      - ./run:/yapi
    networks:
      - yapi-net
    # 初始化
    #command: "yapi server"
    # 日常启动 初始化后生成vendors目录 "/yapi"为9090页面填写的部署路径
    command: "node /yapi/vendors/server/app.js"
networks:
  yapi-net:
    external: true
